/**
 * `GET /api/export?format=md|csv|json`
 *
 * Produces the takeaway artifact: a real, complete settlement statement that
 * downloads and opens. Every format is generated by the same builder as the
 * on-screen statement, so the file and the page can never disagree.
 *
 * `?share=1` returns the JSON envelope inside a stable `Content-Disposition`
 * filename rather than attaching it, which is what the share-link UI needs.
 */

import { NextResponse, type NextRequest } from "next/server";
import { computeSettlement, openSession, queryEntries } from "@/lib/service";
import { buildStatementCsv, buildStatementJson, buildStatementMarkdown, type StatementInput } from "@/lib/statement";
import { ERROR_CODES, errorEnvelope } from "@/lib/validation";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const FORMATS = new Set(["md", "csv", "json"]);

function filenameFor(household: string, format: string, from: string, to: string): string {
  const slug = household.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "khata";
  const ext = format === "md" ? "md" : format;
  return `khata-${slug}-${from}-to-${to}.${ext}`;
}

export async function GET(request: NextRequest) {
  const session = await openSession();
  const format = (request.nextUrl.searchParams.get("format") ?? "md").toLowerCase();

  if (!FORMATS.has(format)) {
    return NextResponse.json(
      errorEnvelope(ERROR_CODES.unsupported, `format must be one of md, csv or json. Received "${format}".`),
      { status: 400 },
    );
  }

  const settlementResult = await computeSettlement(session, { windowDays: "30" });
  if (!settlementResult.ok) return NextResponse.json(settlementResult.response, { status: 400 });

  const { settlement, fx, cpi } = settlementResult.value;
  const { items } = await queryEntries(session, {
    limit: 100, offset: 0, status: "all", direction: "all", category: "all", sort: "occurred_asc",
  });

  const statement: StatementInput = {
    household: session.household,
    entries: items,
    settlement,
    fx: { status: fx.status, asOf: fx.asOf, provider: fx.provider, attribution: fx.attribution },
    cpi,
    generatedAt: new Date().toISOString(),
    seal: settlement.seal ?? "",
  };

  const filename = filenameFor(session.household.name, format, settlement.fromDate, settlement.toDate);

  if (format === "json") {
    return new NextResponse(JSON.stringify(buildStatementJson(statement), null, 2), {
      headers: {
        "content-type": "application/json; charset=utf-8",
        "content-disposition": `attachment; filename="${filename}"`,
        "cache-control": "no-store",
      },
    });
  }

  const body = format === "csv" ? buildStatementCsv(statement) : buildStatementMarkdown(statement);

  if (format === "csv") {
    // A UTF-8 BOM so Excel opens an INR-denominated file without mangling it.
    return new NextResponse(`﻿${body}`, {
      headers: {
        "content-type": "text/csv; charset=utf-8",
        "content-disposition": `attachment; filename="${filename}"`,
        "cache-control": "no-store",
      },
    });
  }

  if (request.nextUrl.searchParams.get("preview") === "1") {
    return NextResponse.json({ ok: true, data: { markdown: body, filename } });
  }

  return new NextResponse(body, {
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "content-disposition": `attachment; filename="${filename}"`,
      "cache-control": "no-store",
    },
  });
}