"use client";

/**
 * The takeaway artifact.
 *
 * Four real outputs, all generated by the same builder as the statement shown
 * here: a Markdown statement, a CSV that opens cleanly in a spreadsheet, a JSON
 * document, and an unguessable share link that renders a read-only statement for
 * whoever you send it to.
 *
 * The downloads are ordinary links to `GET /api/export?format=…`, so they work
 * with JavaScript disabled, get the right filename, and can be curl-ed.
 */

import { useEffect, useState } from "react";
import { Download, FileJson, FileSpreadsheet, Link2, RefreshCw } from "lucide-react";
import { api, errorText } from "@/lib/api";
import { formatStamp } from "@/lib/format";
import { Seal } from "./seal";
import { Failure, Loading, Notice, Rubric } from "./states";
import type { SettlementResponse } from "@/lib/client-types";

interface ShareResult {
  url: string;
  path: string;
  expiresAt: string;
  label: string;
  seal: string;
  warning: string;
}

export function ExportPanel() {
  const [state, setState] = useState<{
    data: SettlementResponse | null;
    error: { message: string; fields?: Record<string, string> } | null;
  }>({ data: null, error: null });
  const [nonce, setNonce] = useState(0);
  const [share, setShare] = useState<ShareResult | null>(null);
  const [sharing, setSharing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [days, setDays] = useState(7);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      const response = await api.get<SettlementResponse>("/api/settlement?windowDays=30");
      if (cancelled) return;
      setState({
        data: response.ok ? response.data : null,
        error: response.ok ? null : { message: errorText(response.error), fields: response.error.fields },
      });
    })();
    return () => {
      cancelled = true;
    };
  }, [nonce]);

  const data = state.data;
  const error = state.error;
  const loading = data === null && error === null;

  const createLink = async () => {
    setSharing(true);
    setCopied(false);
    const response = await api.post<ShareResult>("/api/share", { label: "Settlement statement", days });
    if (response.ok) {
      setShare(response.data);
    } else {
      setState((prev) => ({
        ...prev,
        error: { message: errorText(response.error), fields: response.error.fields },
      }));
    }
    setSharing(false);
  };

  const copy = async () => {
    if (!share) return;
    try {
      await navigator.clipboard.writeText(share.url);
      setCopied(true);
    } catch {
      // Clipboard permission can be refused; the link is on screen either way,
      // so say so rather than pretending it worked.
      setCopied(false);
    }
  };

  return (
    <div className="space-y-6">
      <section className="card p-5" aria-labelledby="downloads">
        <div className="flex flex-wrap items-baseline justify-between gap-2">
          <h2 id="downloads" className="font-display text-2xl text-[color:var(--color-ink-900)]">
            Take it with you
          </h2>
          <button type="button" className="btn btn-quiet" onClick={() => setNonce((n) => n + 1)} disabled={loading}>
            <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} aria-hidden="true" />
            Rebuild
          </button>
        </div>

        <div className="mt-3 grid gap-2 sm:grid-cols-3">
          <a className="btn btn-primary" href="/api/export?format=md" download>
            <Download className="h-4 w-4" aria-hidden="true" /> Markdown statement
          </a>
          <a className="btn btn-quiet" href="/api/export?format=csv" download>
            <FileSpreadsheet className="h-4 w-4" aria-hidden="true" /> CSV for a spreadsheet
          </a>
          <a className="btn btn-quiet" href="/api/export?format=json" download>
            <FileJson className="h-4 w-4" aria-hidden="true" /> JSON for a script
          </a>
        </div>
        <p className="mt-2 text-xs text-[color:var(--color-ink-500)]">
          These are plain links to <span className="font-data">GET /api/export?format=…</span>, so they
          work from a terminal too. The CSV carries a UTF-8 byte-order mark so a spreadsheet opens
          the currency column correctly.
        </p>
      </section>

      <section className="card p-5" aria-labelledby="share">
        <h2 id="share" className="font-display text-2xl text-[color:var(--color-ink-900)]">
          Send it to the other person
        </h2>
        <p className="mt-1 max-w-prose text-sm text-[color:var(--color-ink-700)]">
          A share link renders a read-only statement anyone with the URL can open, with the balances,
          the transfer plan and the seal. It is the argument-ending artefact: they can check the
          number instead of believing it.
        </p>

        <div className="mt-3 flex flex-wrap items-end gap-3">
          <div>
            <label htmlFor="share-days" className="rubric">Open for</label>
            <select id="share-days" className="field mt-1" value={days} onChange={(e) => setDays(Number(e.target.value))}>
              <option value={1}>1 day</option>
              <option value={7}>7 days</option>
              <option value={30}>30 days</option>
            </select>
          </div>
          <button type="button" className="btn btn-primary" onClick={createLink} disabled={sharing}>
            <Link2 className="h-4 w-4" aria-hidden="true" />
            {sharing ? "Minting…" : "Create a statement link"}
          </button>
        </div>

        {share ? (
          <div className="mt-4 space-y-2">
            <Notice tone="warn">{share.warning}</Notice>
            <div className="flex flex-wrap items-center gap-2">
              <code className="min-w-0 flex-1 truncate border border-[color:var(--color-rule)] bg-[color:var(--color-rag-100)] p-2 font-data text-sm">
                {share.url}
              </code>
              <a className="btn btn-quiet" href={share.path} target="_blank" rel="noopener noreferrer">
                Open it
              </a>
              <button type="button" className="btn btn-quiet" onClick={copy}>
                {copied ? "Copied" : "Copy"}
              </button>
            </div>
            <p className="font-data text-xs text-[color:var(--color-ink-500)]">
              Expires {formatStamp(share.expiresAt)} · sealed <Seal seal={share.seal} />
            </p>
          </div>
        ) : null}
      </section>

      {error ? <Failure title="The statement could not be built" message={error.message} fields={error.fields} onRetry={() => setNonce((n) => n + 1)} /> : null}

      {loading && !data ? <Loading label="Building the statement…" /> : null}

      {data ? (
        <section className="card khata-rules p-5" aria-labelledby="preview">
          <div className="flex flex-wrap items-baseline justify-between gap-2">
            <h2 id="preview" className="font-display text-2xl text-[color:var(--color-ink-900)]">
              What is in the file
            </h2>
            <p className="rubric">engine {data.settlement.version}</p>
          </div>

          <h3 className="mt-4 font-display text-xl text-[color:var(--color-ink-900)]">
            {data.settlement.headline}
          </h3>
          <p className="mt-1 text-sm text-[color:var(--color-ink-700)]">
            Trust score {data.settlement.score}/100 over {data.settlement.totals.entryCount} line
            {data.settlement.totals.entryCount === 1 ? "" : "s"}, window {data.settlement.windowDays} days.
          </p>

          <ol className="mt-4 space-y-2">
            <li className="border-b border-[color:var(--color-rule)] pb-2 text-sm text-[color:var(--color-ink-900)]">
              <strong>Who pays whom</strong> — {data.settlement.transferCount} transfer
              {data.settlement.transferCount === 1 ? "" : "s"}
              {data.settlement.minimalTransfers ? ", provably the fewest the balances allow" : ""}.
            </li>
            <li className="border-b border-[color:var(--color-rule)] pb-2 text-sm text-[color:var(--color-ink-900)]">
              <strong>Balances</strong> — what each member paid and what each owes.
            </li>
            <li className="border-b border-[color:var(--color-rule)] pb-2 text-sm text-[color:var(--color-ink-900)]">
              <strong>What the score is made of</strong> — six weighted factors with their evidence.
            </li>
            <li className="border-b border-[color:var(--color-rule)] pb-2 text-sm text-[color:var(--color-ink-900)]">
              <strong>Every line</strong> — date, direction, both amounts, payer, category, decision and
              whether the original message was kept.
            </li>
            <li className="border-b border-[color:var(--color-rule)] pb-2 text-sm text-[color:var(--color-ink-900)]">
              <strong>Where the numbers came from</strong> — exchange rates and consumer prices with
              their status and as-of date.
            </li>
            <li className="text-sm text-[color:var(--color-ink-900)]">
              <strong>The seal</strong> — the full 96-character digest the statement was built from.
            </li>
          </ol>

          <div className="mt-4 border border-[color:var(--color-rule)] bg-[color:var(--color-ink-900)] p-4">
            <Rubric>Seal</Rubric>
            <p className="mt-1 break-all font-data text-xs text-[color:var(--color-rag-100)]">
              {data.settlement.seal ?? "No household events yet, so the chain is still at genesis."}
            </p>
          </div>
        </section>
      ) : null}

      <section className="card p-5" aria-labelledby="disclaimer">
        <h2 id="disclaimer" className="font-display text-2xl text-[color:var(--color-ink-900)]">
          What this is not
        </h2>
        <p className="mt-1 max-w-prose text-sm leading-relaxed text-[color:var(--color-ink-700)]">
          khata is a bookkeeping tool. It records what people in one household tell it and computes
          the arithmetic between those records. It is not a financial adviser, it does not tell you
          what to buy, and a settlement it produces is an agreement between people rather than a
          judgement about money. If two people cannot agree on what happened, khata cannot settle
          that — it can only show what was recorded, when, and whether the record still matches its
          own seal.
        </p>
      </section>
    </div>
  );
}